# Generated by Django 4.2.4 on 2023-10-02 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liabrary',
            fields=[
                ('Section', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('Book_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Auther', models.CharField(max_length=100)),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.liabrary')),
            ],
        ),
    ]
